name : Uthman Action 
run-name : Uthman Action
on : [push]
jobs : 
  Simple_test_for_now :
   runs-on : ubuntu-latest
   steps :
     - name: checkout code from repo
       uses: actions/checkout@v4
    
     - name: Set up Terraform to set up Cloud Infra
       uses: harshicorp/setup-terraform@v2
       with: 
         terraform_version: 1.3.0 

     - name: Terrafrom Initialiazation
       run: terraform init