name : Uthman Action 
run-name : Uthman Action
on : [push]
jobs : 
  Simple_test_for_now :
   runs-on : ubuntu-latest
   steps :
     - name: checkout code from repo
       uses: action/checkout@v4
     - run: echo "hello everyone"
     - run: pwd
     - run: ls