name : Uthman Git Action 
run_name : Uthman Git Action
on : [push]
jobs: 
  Set_test_for_now:
    runs-on: ubuntu-latest
    steps :
     - name: Checkout code for repo
       uses : actions/checkout@v4

     - name: Terraform setup for cloud infra
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0

     - name: Terrraform init
       uses: terraform init
      