name : Uthman Git Action 
run-name : Uthman Git Action
on : [push]

env:
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs: 
  Set_test_for_now:
   runs-on: ubuntu-latest
   steps :
     - name: Checkout code for repo
       uses : actions/checkout@v4

     - name: Terraform setup for cloud infra
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0

     - name: Terrraform init
       run: terraform init -backend-config="bucket=uthman-terraform-bucket" -backend-config="key=dev/terraform.tfstate" -backend-config="region=eu-west-2"

     - name: Terraform plan
       run: terraform plan

     - name: Terraform Apply
       run: terraform apply --auto-approve
      